[project]
name = "content-creation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents[litellm]>=0.6.4",
    "streamlit>=1.52.2",
]
